// Copyright 2016 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto-generated. Do not edit.

package crux

var dataFiles = map[string]string{
	"crux.js": `` +
		`Ly8gQ29weXJpZ2h0IDIwMTYgVGhlIEdvIEF1dGhvcnMuIEFsbCByaWdodHMgcmVzZXJ2ZW` +
		`QuCi8vIFVzZSBvZiB0aGlzIHNvdXJjZSBjb2RlIGlzIGdvdmVybmVkIGJ5IGEgQlNELXN0` +
		`eWxlCi8vIGxpY2Vuc2UgdGhhdCBjYW4gYmUgZm91bmQgaW4gdGhlIExJQ0VOU0UgZmlsZS` +
		`4KZnVuY3Rpb24gZm9yRWFjaFRhYihmbikgewogICAgdmFyIHRhYmxpbmtzID0gZG9jdW1l` +
		`bnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZSgibmF2dGFiIik7CiAgICBmb3IgKHZhciBpID` +
		`0gMDsgaSA8IHRhYmxpbmtzLmxlbmd0aDsgaSsrKSB7CiAgICAgICAgdmFyIHRhYmxpbmsg` +
		`PSB0YWJsaW5rcy5pdGVtKGkpOwogICAgICAgIHZhciBuYW1lID0gdGFibGluay5pbm5lck` +
		`hUTUw7CiAgICAgICAgZm4obmFtZSwgdGFibGluayk7CiAgICB9Cn0KZnVuY3Rpb24gZm9y` +
		`RWFjaFBhZ2UoZm4pIHsKICAgIHZhciBtYWluID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SW` +
		`QoIm1haW4iKTsKICAgIGZvciAodmFyIGkgPSAwOyBpIDwgbWFpbi5jaGlsZHJlbi5sZW5n` +
		`dGg7IGkrKykgewogICAgICAgIHZhciBwYWdlID0gbWFpbi5jaGlsZHJlbltpXTsKICAgIC` +
		`AgICBmbihwYWdlLmlkLCBwYWdlKTsKICAgIH0KfQpmdW5jdGlvbiB0b2dnbGVQYWdlKHBh` +
		`Z2VuYW1lKSB7CiAgICBmb3JFYWNoUGFnZShmdW5jdGlvbiAobmFtZSwgcGFnZSkgewogIC` +
		`AgICAgIGlmIChuYW1lID09IHBhZ2VuYW1lKSB7CiAgICAgICAgICAgIGlmIChwYWdlLnN0` +
		`eWxlLmRpc3BsYXkgIT0gImJsb2NrIikgewogICAgICAgICAgICAgICAgcGFnZS5zdHlsZS` +
		`5kaXNwbGF5ID0gImJsb2NrIjsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgICAgICBl` +
		`bHNlIHsKICAgICAgICAgICAgcGFnZS5zdHlsZS5kaXNwbGF5ID0gIm5vbmUiOwogICAgIC` +
		`AgIH0KICAgIH0pOwp9CmZ1bmN0aW9uIHRhYkJvZHkobmFtZSkgewogICAgcmV0dXJuIGRv` +
		`Y3VtZW50LmdldEVsZW1lbnRCeUlkKCJuYXYiICsgbmFtZSk7Cn0KZnVuY3Rpb24gbmF2Z2` +
		`8obmFtZSkgewogICAgZm9yRWFjaFRhYihmdW5jdGlvbiAodG5hbWUsIGxpbmspIHsKICAg` +
		`ICAgICB2YXIgYm9keSA9IHRhYkJvZHkodG5hbWUpOwogICAgICAgIGlmICh0bmFtZSA9PS` +
		`BuYW1lKSB7CiAgICAgICAgICAgIGJvZHkuc3R5bGUuZGlzcGxheSA9ICJibG9jayI7CiAg` +
		`ICAgICAgICAgIGxpbmsuY2xhc3NMaXN0LmFkZCgibmF2dGFiY3VycmVudCIpOwogICAgIC` +
		`AgIH0KICAgICAgICBlbHNlIHsKICAgICAgICAgICAgYm9keS5zdHlsZS5kaXNwbGF5ID0g` +
		`Im5vbmUiOwogICAgICAgICAgICBsaW5rLmNsYXNzTGlzdC5yZW1vdmUoIm5hdnRhYmN1cn` +
		`JlbnQiKTsKICAgICAgICB9CiAgICB9KTsKICAgIGlmIChuYW1lID09ICJzdGF0cyIpIHsK` +
		`ICAgICAgICBsb2FkTG9nTmFtZXMoKTsKICAgIH0KfQpmdW5jdGlvbiBoYW5kbGVMb2codG` +
		`V4dCkgewp9CmZ1bmN0aW9uIGxvYWRMb2cobG9nbmFtZSkgewogICAgY29uc29sZS5sb2co` +
		`ImxvYWRMb2ciLCBsb2duYW1lKTsKICAgIHRvZ2dsZVBhZ2UoIm1haW5sb2dzIik7CiAgIC` +
		`B2YXIgeGhyID0gbmV3IFhNTEh0dHBSZXF1ZXN0KCk7CiAgICAvLyBUT0RPOiBvZmZzZXQs` +
		`IGxpbWl0CiAgICB4aHIub3BlbigiR0VUIiwgIi9kZWJ1Zy9jcnV4L2xvZ3MvIiArIGxvZ2` +
		`5hbWUpOwogICAgeGhyLm9ubG9hZCA9IGZ1bmN0aW9uIChldikgewogICAgICAgIGlmICh4` +
		`aHIuc3RhdHVzIDwgMjAwIHx8IHhoci5zdGF0dXMgPj0gMzAwKSB7CiAgICAgICAgICAgIG` +
		`NvbnNvbGUubG9nKCJiYWQgZGF0YToiLCB4aHIpOwogICAgICAgICAgICByZXR1cm47CiAg` +
		`ICAgICAgfQogICAgICAgIHZhciBtYWluID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoIm` +
		`1haW4iKTsKICAgICAgICB2YXIgYXRCb3R0b20gPSBtYWluLnNjcm9sbEhlaWdodCAtIG1h` +
		`aW4uc2Nyb2xsVG9wID09IG1haW4uY2xpZW50SGVpZ2h0OwogICAgICAgIHZhciBtYWlubG` +
		`9ncyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJtYWlubG9ncyIpOwogICAgICAgIG1h` +
		`aW5sb2dzLmlubmVySFRNTCA9ICI8cHJlIGlkPVwibG9nXCI+IiArIHhoci5yZXNwb25zZV` +
		`RleHQgKyAiPC9wcmU+IjsKICAgICAgICBpZiAoYXRCb3R0b20pIHsKICAgICAgICAgICAg` +
		`bWFpbi5zY3JvbGxUb3AgPSBtYWluLnNjcm9sbEhlaWdodCAtIG1haW4uY2xpZW50SGVpZ2` +
		`h0OwogICAgICAgIH0KICAgIH07CiAgICB4aHIub25lcnJvciA9IGZ1bmN0aW9uIChldikg` +
		`eyB4aHJFcnJvcigibG9nIiwgZXYpOyB9OwogICAgeGhyLnNlbmQoKTsKICAgIHdpbmRvdy` +
		`5jbGVhckludGVydmFsKGN1clJlZnJlc2hJRCk7CiAgICBjdXJSZWZyZXNoSUQgPSB3aW5k` +
		`b3cuc2V0SW50ZXJ2YWwobG9hZExvZywgMTAwMCwgbG9nbmFtZSk7Cn0KdmFyIGN1clJlZn` +
		`Jlc2hJRDsKZnVuY3Rpb24gaGFuZGxlTG9nTmFtZXMoZmlsZXMpIHsKICAgIHZhciBsb2dz` +
		`bGlzdCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJsb2dzbGlzdCIpOwogICAgbG9nc2` +
		`xpc3QuaW5uZXJIVE1MID0gIiI7CiAgICBmb3IgKHZhciBfaSA9IDA7IF9pIDwgZmlsZXMu` +
		`bGVuZ3RoOyBfaSsrKSB7CiAgICAgICAgdmFyIGZpbGUgPSBmaWxlc1tfaV07CiAgICAgIC` +
		`AgbG9nc2xpc3QuaW5uZXJIVE1MICs9ICI8bGk+PGEgY2xhc3M9XCJsb2dzbGlua1wiPiIg` +
		`KyBmaWxlICsgIjwvYT48L2xpPiI7CiAgICB9CiAgICBmb3IgKHZhciBpID0gMDsgaSA8IG` +
		`xvZ3NsaXN0LmNoaWxkcmVuLmxlbmd0aDsgaSsrKSB7CiAgICAgICAgdmFyIGxpID0gbG9n` +
		`c2xpc3QuY2hpbGRyZW5baV07CiAgICAgICAgbGkuY2hpbGRyZW5bMF0uYWRkRXZlbnRMaX` +
		`N0ZW5lcignY2xpY2snLCBmdW5jdGlvbiAoZSkgewogICAgICAgICAgICB2YXIgbmFtZSA9` +
		`IGUudGFyZ2V0LmlubmVySFRNTDsKICAgICAgICAgICAgbG9hZExvZyhuYW1lKTsKICAgIC` +
		`AgICB9KTsKICAgIH0KfQpmdW5jdGlvbiBsb2FkU3RhdHMoKSB7CiAgICB0b2dnbGVQYWdl` +
		`KCJtYWluc3RhdHMiKTsKICAgIHZhciB4aHIgPSBuZXcgWE1MSHR0cFJlcXVlc3QoKTsKIC` +
		`AgIHhoci5vcGVuKCJHRVQiLCAiL2RlYnVnL2NydXgvc3RhdHMiKTsKICAgIHhoci5vbmxv` +
		`YWQgPSBmdW5jdGlvbiAoZXYpIHsKICAgICAgICBpZiAoeGhyLnN0YXR1cyA8IDIwMCB8fC` +
		`B4aHIuc3RhdHVzID49IDMwMCkgewogICAgICAgICAgICBjb25zb2xlLmxvZygiYmFkIGRh` +
		`dGE6IiwgeGhyKTsKICAgICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KICAgICAgICBkb2` +
		`N1bWVudC5nZXRFbGVtZW50QnlJZCgibWFpbnN0YXRzIikuaW5uZXJIVE1MID0geGhyLnJl` +
		`c3BvbnNlVGV4dDsKICAgIH07CiAgICB4aHIub25lcnJvciA9IGZ1bmN0aW9uIChldikgey` +
		`B4aHJFcnJvcigic3RhdHMiLCBldik7IH07CiAgICB4aHIuc2VuZCgpOwogICAgd2luZG93` +
		`LmNsZWFySW50ZXJ2YWwoY3VyUmVmcmVzaElEKTsKICAgIC8vY3VyUmVmcmVzaElEID0gd2` +
		`luZG93LnNldEludGVydmFsKGxvYWRTdGF0cywgNTAwMCk7Cn0KZnVuY3Rpb24geGhyRXJy` +
		`b3IobmFtZSwgZXYpIHsKICAgIC8vIFRPRE86IHZpc2libGUgdXNlciBmZWVkYmFjawogIC` +
		`AgY29uc29sZS5sb2coImxvYWRpbmcgIiArIG5hbWUgKyAiIGZhaWxlZDogIiwgZXYpOwp9` +
		`CmZ1bmN0aW9uIGxvYWRMb2dOYW1lcygpIHsKICAgIHZhciB4aHIgPSBuZXcgWE1MSHR0cF` +
		`JlcXVlc3QoKTsKICAgIHhoci5vcGVuKCJHRVQiLCAiL2RlYnVnL2NydXgvbG9ncy9saXN0` +
		`Iik7CiAgICB4aHIub25sb2FkID0gZnVuY3Rpb24gKGV2KSB7CiAgICAgICAgaWYgKHhoci` +
		`5zdGF0dXMgPCAyMDAgfHwgeGhyLnN0YXR1cyA+PSAzMDApIHsKICAgICAgICAgICAgY29u` +
		`c29sZS5sb2coImJhZCBkYXRhOiIsIHhocik7CiAgICAgICAgICAgIHJldHVybjsKICAgIC` +
		`AgICB9CiAgICAgICAgdmFyIHJlcyA9IEpTT04ucGFyc2UoeGhyLnJlc3BvbnNlVGV4dCk7` +
		`CiAgICAgICAgaGFuZGxlTG9nTmFtZXMocmVzLkZpbGVzKTsKICAgIH07CiAgICB4aHIub2` +
		`5lcnJvciA9IGZ1bmN0aW9uIChldikgeyB4aHJFcnJvcigibG9ncyBsaXN0IiwgZXYpOyB9` +
		`OwogICAgeGhyLnNlbmQoKTsKfQp3aW5kb3cub25sb2FkID0gZnVuY3Rpb24gKCkgewogIC` +
		`AgZm9yRWFjaFRhYihmdW5jdGlvbiAobmFtZSwgbGluaykgewogICAgICAgIGxpbmsuYWRk` +
		`RXZlbnRMaXN0ZW5lcignY2xpY2snLCBmdW5jdGlvbiAoZSkgewogICAgICAgICAgICBuYX` +
		`ZnbyhuYW1lKTsKICAgICAgICB9KTsKICAgIH0pOwogICAgdmFyIHNob3dzdGF0cyA9IGRv` +
		`Y3VtZW50LmdldEVsZW1lbnRCeUlkKCJzaG93c3RhdHMiKTsKICAgIHNob3dzdGF0cy5hZG` +
		`RFdmVudExpc3RlbmVyKCJjbGljayIsIGZ1bmN0aW9uIChlKSB7CiAgICAgICAgbG9hZFN0` +
		`YXRzKCk7CiAgICB9KTsKICAgIG5hdmdvKCJzdGF0cyIpOwogICAgbG9hZFN0YXRzKCk7Cn` +
		`07Cg==` +
		``,
	"crux.html": `` +
		`PCFET0NUWVBFIGh0bWw+CjxodG1sPgo8aGVhZD4KPCEtLQpDb3B5cmlnaHQgMjAxNiBUaG` +
		`UgR28gQXV0aG9ycy4gQWxsIHJpZ2h0cyByZXNlcnZlZC4KVXNlIG9mIHRoaXMgc291cmNl` +
		`IGNvZGUgaXMgZ292ZXJuZWQgYnkgYSBCU0Qtc3R5bGUKbGljZW5zZSB0aGF0IGNhbiBiZS` +
		`Bmb3VuZCBpbiB0aGUgTElDRU5TRSBmaWxlLgotLT4KPHRpdGxlPmNydXg8L3RpdGxlPgo8` +
		`c3R5bGU+Cmh0bWwgeyBvdmVyZmxvdzogaGlkZGVuOyB9CmJvZHkgewoJZm9udC1mYW1pbH` +
		`k6IHNhbnMtc2VyaWY7Cglmb250LXNpemU6IDEycHg7CgltYXJnaW46MDsKfQoKI2NvbHMg` +
		`ewoJZGlzcGxheTogZmxleDsKCWZsZXgtZGlyZWN0aW9uOiByb3c7CgloZWlnaHQ6IDEwMH` +
		`ZoOwp9CgojbmF2IHsKCXdpZHRoOiAyMDBweDsKCWhlaWdodDogMTAwdmg7CglkaXNwbGF5` +
		`OiBmbGV4OwoJZmxleC1kaXJlY3Rpb246IGNvbHVtbjsKCW92ZXJmbG93OiBoaWRkZW47Cg` +
		`lyZXNpemU6IGhvcml6b250YWw7IC8qIFRPRE8gZG9lc24ndCB3b3JrICovCglib3JkZXIt` +
		`cmlnaHQ6IDFweCBzb2xpZCBncmF5OwoJYmFja2dyb3VuZC1jb2xvcjogI2VlZTsKfQojbm` +
		`F2aGVhZGVyIHsKCWJvcmRlci1ib3R0b206IDFweCBzb2xpZCBncmF5OwoJcGFkZGluZzog` +
		`NXB4Owp9CgoubmF2dGFicGFuZWwgewoJZmxleC1ncm93OiAxOwoJb3ZlcmZsb3cteTogc2` +
		`Nyb2xsOwoJcGFkZGluZzogNXB4OwoJYmFja2dyb3VuZC1jb2xvcjogI2YzZjNmMzsKCWJv` +
		`cmRlci1ib3R0b206IDFweCBzb2xpZCBncmF5Owp9CgojbmF2c3RhdHMgewp9CiNuYXZnb3` +
		`JvdXRpbmVzIHsKCWRpc3BsYXk6IG5vbmU7Cn0KI25hdmZvb3RlciB7Cgl3aWR0aDogMTAw` +
		`cHg7CglwYWRkaW5nOiA1cHg7Cn0KCiNuYXYgdWwgewoJcGFkZGluZzogMDsKfQojbmF2IH` +
		`VsIHVsIHsKCXBhZGRpbmctbGVmdDogMWVtOwp9CgojbmF2IHVsIGxpIHsKCWxpc3Qtc3R5` +
		`bGU6IHNxdWFyZSBpbnNpZGU7Cn0KI25hdiB1bCBsaSB1bCBsaSB7CglsaXN0LXN0eWxlOi` +
		`Bub25lOwp9CmEgewoJdGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7Cgljb2xvcjogYmx1` +
		`ZTsKCWN1cnNvcjogcG9pbnRlcjsKfQoubmF2dGFiY3VycmVudCB7Cgl0ZXh0LWRlY29yYX` +
		`Rpb246IG5vbmU7Cgljb2xvcjogYmxhY2s7CgljdXJzb3I6IGRlZmF1bHQ7Cn0KCiNtYWlu` +
		`IHsKCW92ZXJmbG93OiBzY3JvbGw7CglwYWRkaW5nOiA1cHg7CglmbGV4LWdyb3c6IDE7Cn` +
		`0KI21haW5zdGF0cyB7fQojbWFpbmxvZ3MgeyBkaXNwbGF5OiBub25lOyB9Cgp0aCB7IHRl` +
		`eHQtYWxpZ246IGxlZnQ7IH0KCiNlbnYgewoJd2lkdGg6IDUwdnc7Cgl0YWJsZS1sYXlvdX` +
		`Q6IGZpeGVkOwp9CiNlbnYgdGggeyBmb250LXdlaWdodDogbm9ybWFsOyB9CiNlbnYgdGQg` +
		`eyB3b3JkLXdyYXA6IGJyZWFrLXdvcmQ7IH0KPC9zdHlsZT4KPHNjcmlwdCBzcmM9ImNydX` +
		`guanMiPjwvc2NyaXB0Pgo8L2hlYWQ+Cjxib2R5PgoKPGRpdiBpZD0iY29scyI+Cgo8ZGl2` +
		`IGlkPSJuYXYiPgoKPGRpdiBpZD0ibmF2aGVhZGVyIj4KPGEgY2xhc3M9Im5hdnRhYiI+c3` +
		`RhdHM8L2E+IHwKPGEgY2xhc3M9Im5hdnRhYiI+Z29yb3V0aW5lczwvYT4KPC9kaXY+Cgo8` +
		`ZGl2IGlkPSJuYXZzdGF0cyIgY2xhc3M9Im5hdnRhYnBhbmVsIj4KPGEgaWQ9InNob3dzdG` +
		`F0cyI+c3RhdHM8L2E+PGJyPgo8Yj5sb2dzPC9iPgo8dWwgaWQ9ImxvZ3NsaXN0Ij4KPC91` +
		`bD4KPC9kaXY+Cgo8ZGl2IGlkPSJuYXZnb3JvdXRpbmVzIiBjbGFzcz0ibmF2dGFicGFuZW` +
		`wiPgo8dWw+CjxsaT4xOiBjcnV4LkxvYWQKPHVsPgoJPGxpPm1haW4ubWFpbjwvbGk+Cjwv` +
		`dWw+CjwvbGk+CjxsaT41NzQzNDogbWFpbi5mdW5jMQo8dWw+Cgk8bGk+bWFpbi5tYWluIC` +
		`hjcmVhdGVkIGJ5KTwvbGk+CjwvdWw+CjwvbGk+CjwvdWw+CjwvZGl2PgoKPGRpdiBpZD0i` +
		`bmF2Zm9vdGVyIj4KY3J1eAo8L2Rpdj4KPC9kaXY+Cgo8ZGl2IGlkPSJtYWluIj4KCTxkaX` +
		`YgaWQ9Im1haW5zdGF0cyI+PCEtLSBUT0RPIHBvcHVsYXRlIG9uIGluaXRpYWwgbG9hZCAt` +
		`LT48L2Rpdj4KCTxkaXYgaWQ9Im1haW5sb2dzIj48L2Rpdj4KPC9kaXY+Cgo8L2Rpdj4KPC` +
		`9ib2R5Pgo8L2h0bWw+Cg==` +
		``,
}
